Create ADR template with first decision: Secure developer package supply
Azure/terraform-azurerm-avm-ptn-ai-reference-implementation pull request #25
Opened 2024-08-19 10:59 UTC by shanepeckham

## Description
Closes #110

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [X] My corresponding pipelines / checks run clean and green without any errors or warnings
- [X] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-08-19 19:06 UTC, Nepomuceno commented
Should we keep all the ADR in one file or create a folder for the ARD and put each decision in one file? just worried this file could get really big.

2024-08-20 01:02 UTC, noodlefrenzy requested changes
Little comment on the content since much of it stems from the discussion in Teams, mostly commenting on how to ensure you get the right structure for mADRs in place.

2024-08-20 01:02 UTC, noodlefrenzy commented on adr.md
> +* If not implemented, a customer's development packages can pose a security risk if the provenance and package is not vetted.
If _what_ not implemented? I would go into a bit more detail here that a more robust solution would need to be implemented for a customer to take it to production.

2024-08-20 07:42 UTC, shanepeckham commented on adr.md
> +* Containerize solutions all solutions built on AIRI. Container image scanning will be required and customers may already have a solution in place.Conforming to the first principles of the AIRI proje
Implemented

2024-08-20 08:54 UTC, shanepeckham commented
> Should we keep all the ADR in one file or create a folder for the ARD and put each decision in one file? just worried this file could get really big.

For now we will, but we can look to create a new one per milestone, period etc. Let's solve that later

2024-08-20 09:10 UTC, noodlefrenzy commented
@Nepomuceno we should be breaking them out into their own directory - the Markdown ADR repo (where I advised Shane to get the template) has a good demonstration of the structure: https://github.com/adr/madr/tree/3.0.0-beta.2/docs/decisions

2024-08-20 09:13 UTC, noodlefrenzy commented
Basically, create a ~/docs/decisions/ or ~/docs/adrs/ directory, and store all ADRs under there. Each decision is its own file, versioned. Not only that, but even if you reconsider a previous decision, you _never_ alter the original file once it's been decided other than to mark it as deprecated and point it to a new file with the revised decision.

e.g. :
- 0005-tabs-vs-spaces-use-tabs.md
- ...
- 0008-tabs-vs-spaces-use-spaces-instead.md
(you'd create a new file with the revised decision, and change the status on the previous one)

2024-08-21 14:16 UTC, martinpeck commented on adr.md
> +# These are optional elements. Feel free to remove any of them.
should remove these

2024-08-21 14:16 UTC, martinpeck commented on adr.md
> +### Allow outbound access from AML/AI Studio
Suggest moving this to the top, so that the chosen option is first

2024-08-21 14:16 UTC, martinpeck commented on adr.md
> +* Allow outbound access from AML/AI Studio
suggest moving this to the top so the chosen option is first

2024-08-21 14:17 UTC, martinpeck commented
Agree with comments above regarding the creation of a folder structure.
These files shouldn't sit in the root.

2024-08-21 18:34 UTC, shanepeckham commented on adr.md
> +# Configuration for the Jekyll template "Just the Docs"
Addressed

2024-08-21 18:34 UTC, shanepeckham commented on adr.md
> +# These are optional elements. Feel free to remove any of them.
Removed

2024-08-21 18:35 UTC, shanepeckham commented on adr.md
> +Allow outbound access from AML/AI Studio but include in the documentation that this will need to be disabled off for all environments.
Corrected

2024-08-21 18:36 UTC, shanepeckham commented on adr.md
> +### Allow outbound access from AML/AI Studio
Moved

2024-08-21 18:37 UTC, shanepeckham commented on adr.md
> +* Allow outbound access from AML/AI Studio
Moved

2024-08-21 18:37 UTC, shanepeckham commented on adr.md
> +# Configuration for the Jekyll template "Just the Docs"
Removed

2024-08-23 09:27 UTC, merged