Adding VPN
Azure/terraform-azurerm-avm-ptn-ai-reference-implementation pull request #26
Opened 2024-08-19 11:20 UTC by Nepomuceno

## Description

Adding VPN to help us support 

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - x ] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-08-19 12:41 UTC, shanepeckham commented on README.md
> +Default: `true`
This should be optional though right? It needs to be false by default and we should set it to true for our deployments.

2024-08-19 12:53 UTC, Nepomuceno commented on README.md
> +Default: `true`
perfect will set the defualt to false but I can put to true in the examples folder

2024-08-19 19:42 UTC, PabloZaiden commented on examples/default/README.md
> +  create_vpn          = true
Should the default example have both the vpn and jumpbox enabled?

2024-08-19 19:42 UTC, PabloZaiden commented on modules/vpn/variables.tf
> +  default     = ["192.168.0.0/24"]
Wouldn't this (very common) default address space be likely to collide with the address space of the client's network?

2024-08-19 19:43 UTC, Nepomuceno commented on modules/vpn/variables.tf
> +  default     = ["192.168.0.0/24"]
This si the default on the portal normally and on the documentation that is why I didput the same here. Hopefully if the customer has this he would not be creating this vpn

2024-08-19 19:44 UTC, Nepomuceno commented on examples/default/README.md
> +  create_vpn          = true
I think for now we are using example as our testbed when we do have one of those 2 working correctly we can disable the other.

2024-08-19 19:44 UTC, PabloZaiden approved these changes

2024-08-19 22:50 UTC, vyta requested changes
Thanks for this @Nepomuceno! I have some questions regarding the dns resolver, and more generally making sure we can get the VPN solution working e2e before merging since you have not been able to access the workspace with VPN at the moment.

2024-08-19 22:50 UTC, vyta commented on modules/vpn/_header.md
> +# Vpn Intenral Module for the patttern.
```suggestion
# Internal VPN Module for the pattern
```

2024-08-19 22:50 UTC, vyta commented on modules/vpn/main.tf
> +resource "azurerm_private_dns_resolver" "base" {
I see the resolver but no rules, is the resolver required for VPN?

2024-08-19 22:50 UTC, vyta commented on modules/vpn/main.tf
> +resource "azurerm_private_dns_resolver_inbound_endpoint" "base" {
If resolver is required, do we need output endpoint as well for dns resolver?

2024-08-20 20:58 UTC, vyta requested changes
Thanks @Nepomuceno, just a couple comments

2024-08-20 20:58 UTC, vyta commented on variables.tf
> +variable "vm_network_security_group" {
I think we want to enforce NSG on the subnet (general security guidance), but make the rules configurable, no?

2024-08-20 21:35 UTC, vyta approved these changes

2024-08-20 22:16 UTC, merged