chore: repository governance
Azure/terraform-azurerm-avm-ptn-ai-reference-implementation pull request #40
Opened 2024-08-25 01:50 UTC by segraef

## Repository governance update

This PR was automatically created by the AVM Team hive-mind using the [grept](https://github.com/Azure/grept) governance tool.

We have detected that some files need updating to meet the AVM governance standards.
Please review and merge with alacrity.

Grept config source: `git::https://github.com/Azure/Azure-Verified-Modules-Grept.git//terraform`

Thanks! The AVM team :heart:

2024-08-28 09:11 UTC, martinpeck requested changes

2024-08-28 09:11 UTC, martinpeck commented on README.md
> -## Architecture Design Record
Why was this removed?

2024-08-28 09:11 UTC, martinpeck commented on README.md
> -## Architecture Design Record
Suggest reverting this change, unless it's somehow related to repository governance

2024-08-29 03:04 UTC, mbilalamjad approved these changes
Please ensure all checks pass before merging.

2024-09-01 01:27 UTC, segraef commented
Supersceeded by #50

2024-09-01 01:27 UTC, closed without merging